image: java:8
before_script:
- apt-get update -y
- apt-get install apt-transport-https -y
- echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
- apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
- apt-get update -y
- apt-get install maven -y
- sbt sbt-version
test:
  script:
  - cd chatbot
  - mvn clean test
